### ISSUE TITLE
Build failing for iOS device on Mac

### ISSUE THREAD

**Issue by nadirlaskar** [onepanelio/demo-app#2]
On Running the command `react-native run-ios --simulator="iPhone 11 pro" `

The build steps are failing with the following error
```
../../react-native/React/Base/RCTBridgeModule.h:10:9: fatal error: 'React/RCTDefines.h' file not found
#import <React/RCTDefines.h>
        ^~~~~~~~~~~~~~~~~~~~
1 error generated.


** BUILD FAILED **


The following build commands failed:
	CompileC /Users/****/Desktop/demo-app/ios/build/platform_demo/Build/Intermediates.noindex/TfliteReactNative.build/Debug-iphonesimulator/TfliteReactNative.build/Objects-normal/x86_64/TfliteReactNative.o /Users/infinitejock/Desktop/demo-app/node_modules/tflite-react-native/ios/TfliteReactNative.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

The error is from [tflite-react-native](https://www.npmjs.com/package/tflite-react-native) module
which implements a cross-platform bridge from react to the native implementation of tflite.

The [issue ](https://github.com/shaqian/tflite-react-native/issues/11 )is already open in [tflite-react-native](https://github.com/shaqian/tflite-react-native) github repository.

**### UPDATE**
There seems to be a [pull request](https://github.com/shaqian/tflite-react-native/pull/13) with the fix available.

**Comment by nadirlaskar** [comment]
Currently using this pull request [repo](https://github.com/kaelhem/tflite-react-native), it is working fine waiting for an update with the fix from [tflite-react-native](https://www.npmjs.com/package/tflite-react-native)  

I will close the issue once the update is available from [tflite-react-native](https://www.npmjs.com/package/tflite-react-native)  module.

**Comment by joinalahmed** [comment]
Closing this as fixed.
